### PR TITLE
Update `flex` parser

### PR DESCRIPTION
**Pull request by peduarte**
This PR fixes the parsing of `flex` property

### CODE REVIEW

**Review by jonathantneal — COMMENTED** [review]
- [x] Initial code review 👍

**Review by jonathantneal — APPROVED** [review]
- [x] Code review 👍
- [x] Checkout review 👍

🚢 Love it! ♥❤️﻿

**Review by hadihallak — APPROVED** [review]
LGTM ✅ 

@jonathantneal 
I think we should start to experiment with moving the shorthand parsing outside the library as a plugin of some sort because all throughout our shorthand parsing we have cases like this where we're not following the CSS spec 1:1 and we're not generating full longhands that include setting defaults and since doing so we are likely to increase the bundle size then it would be very good if we could separate this into its own plugin or package.
curious to know your thoughts about this

**Comment by jonathantneal** [comment]
@hadihallak strong agree, next canary? 😄 let’s discuss next.

**Pull request merged**
