### PR TITLE
Setup CodeSandbox CI

### LINKED ISSUE #163: Integrate codesandbox with this repo
We need to integrate codesandbox in a way where each PR is built and deployed to a codesandbox to allow for quick testing and validation of PRs

### PR DESCRIPTION
**Pull request by peduarte**
🚀 Closes #163

### CODE REVIEW

**Comment by vivek12345** [comment]
This is awesome 🎉

**Comment by peduarte** [comment]
@vivek12345 doesnt seem to be working on PRs created by other people. For example #202 

do you know why?

**Comment by vivek12345** [comment]
Not too sure but the only thing that comes to my mind is that PR should take a pull from canary post your merge of codesandbox ci changes

**Comment by cometkim** [comment]
Nice! It would be even nicer if we have it for Gatsby!

[The plugin](https://github.com/cometkim/gatsby-theme-stitches) is working on `gatsby build` as well since v0.0.2

**Comment by peduarte** [comment]
Yeah, I'm gonna set up one for Gatsby too!

**Pull request merged**
