### PR TITLE
Add text-size-adjust webkit prefix

### PR DESCRIPTION
**Pull request by rafgraph**

### CODE REVIEW

**Review by peduarte — APPROVED** [review]

**Comment by jonathantneal** [comment]
Hey @rafgraph, thanks for the clean and clear PR.

Does Firefox or Safari support `text-size-adjust` in the same way as Edge or Chrome? If so, would you be able to provide an example?

<picture><source type="image/webp" srcset="https://caniuse.bitsofco.de/image/text-size-adjust.webp"><source type="image/png" srcset="https://caniuse.bitsofco.de/image/text-size-adjust.png">Data on support for the text-size-adjust feature across the major browsers from caniuse.com</picture>

See:

- [`text-size-adjust` at **caniuse**](https://caniuse.com/text-size-adjust)
- [`text-size-adjust` at **mdn**](https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust)

**Comment by rafgraph** [comment]
Yes, iOS safari and Firefox on Android do (with prefix).

Screen Shot 2021-06-02 at 10 38 22 AM

**Comment by jonathantneal** [comment]
Hey @rafgraph, I just remembered that we removed `text-size-adjust` from [normalize.css](https://github.com/csstools/normalize.css/blob/4867dabf66ec31c4b7b5be2a92ddee46075a7f40/CHANGELOG.md#head) and [cssremedy](https://github.com/jensimmons/cssremedy/commit/3a9c7e3331c10eee3680e64bef1dad441b27c1b4) because it is no longer applicable.

I don’t think we should add a defunct property. If you can show that it is still being applied, tho, please share an example so we can bring it to the attention of cssremedy and normalize.css!

**Comment by rafgraph** [comment]
Hi @jonathantneal, where did you hear it is no longer applicable? It still works on iOS safari (latest version, iPro 12 pro). [Here's a codesandbox](https://codesandbox.io/s/boring-merkle-vvk0w?file=/src/styles.css), on iOS safari view just the site, https://vvk0w.csb.app/, and rotate the screen (text inflates in landscape mode). The text will not inflate when  `-webkit-text-size-adjust: none; ` is not commented out. I didn't test FireFox on android (I was going by CanIUse for that prefix), so maybe that's no longer applicable.

**Comment by rafgraph** [comment]
Also see: https://github.com/jensimmons/cssremedy/issues/13#issuecomment-855256146

**Comment by rafgraph** [comment]
@jonathantneal why was this closed without merging?

**Comment by jonathantneal** [comment]
The manual merge failed (and it had required a manual merge), so while the fix made it into production, there was no signal to GitHub to correctly preserve your commit or your PR. 🙃

Just above your comment, you should see that it was closed in https://github.com/modulz/stitches/commit/db468ab31dc03a662e7545ecd44cfc796bd78a58.

**Comment by rafgraph** [comment]
It looks like you just copied the code from this PR into https://github.com/modulz/stitches/commit/db468ab31dc03a662e7545ecd44cfc796bd78a58 🤷‍♂️

**Comment by jonathantneal** [comment]
@rafgraph, yes it looks copied because it’s your code, and you deserve the credit for it! If there’s any way we can get your username attached to a commit on it, let’s do it. I’m very sorry I could not merge it. It was unfortunate that I did not know you were available on such short notice, as you could have at least reset and signed a new commit. I hope we can do more, but for now, anyone who sees this should know you discovered the issue; and it was an issue **most people thought had been resolved for 2 years**.

For future reference, visitors from the future, this was an older PR with merge conflicts that, for whatever reason I could not manually rebase in limited time with VSCode, nor automatically rebase with GitHub’s built in tooling. Locally, it would get stuck at a point where git marked nearly every file in the repository as having been changed. The reason the PR was originally withheld from merging was because it seemed like an unnecessary fix to a non-issue. However, @rafgraph actually discovered an issue many projects & maintainers (including myself) had thought was resolved back in February of 2019. I was so surprised when I tested your reproduction and watched the old issue persist. I have also since backed up your claim on https://github.com/jensimmons/cssremedy/issues/13. I’ll need to patch normalize.css & sanitize.css, too.

If you think there’s a way we can get your name back on these changes or at least on the project, please let me know.

**Pull request closed without merging**
