### PR TITLE
Improve check for cssRules access

### PR DESCRIPTION
**Pull request by megawebmaster**
Hi! :wave: 

I was hit by a bug with checking access for `cssRules` property on existing CSS style or link tags: https://github.com/modulz/stitches/issues/756 It was a real problem for me as I'm introducing Stitches to my project (it uses existing styles for other parts of the system) and we rely on Storybook (which renders components in an iframe) to get the UI elements right.

To avoid having problems I propose to improve how Stitches check for access to `cssRules` property on `CSSStyleSheet` objects to also include a try to access them and bail out if we catch an exception based on how this object should behave: https://drafts.csswg.org/cssom/#the-cssstylesheet-interface

I decided to keep earlier check as it should be easier and faster to process in most cases (as it is working in current code).

### CODE REVIEW

**Comment by megawebmaster** [comment]
@peduarte - how is this going? I'm a bit worried, as I received a few production errors from Rollbar about "SecurityError: CSSStyleSheet.cssRules getter: Not allowed to access cross-origin stylesheet". 

If you still need some additional time I'll just use my branch for the time being and switch back when the issue is resolved :+1:

**Comment by peduarte** [comment]
@hadihallak would you be able to review this if you have a chance? Thanks!

**Comment by hadihallak** [comment]
@megawebmaster Thank you so much for looking into this and working on a fix 🙏 
will be reviewing it later today.

**Comment by hadihallak** [comment]
Hey @megawebmaster 
the code looks great aside from some indentation changes but I would be very helpful if you could provide a minimal reproduction of the issue as I think I might be able to handle it elsewhere and having a reproduction will help me make sure it's tested in the codebase.
 
Thanks again for submitting the PR. Very appreciated.

**Comment by megawebmaster** [comment]
Hey @hadihallak

I will try to prepare something for you.

**Comment by hadihallak** [comment]
@megawebmaster Amazing! thank you so much 🙏

**Comment by megawebmaster** [comment]
@hadihallak - here's a repo with the issue: https://github.com/megawebmaster/stitches-cssrules-reproduction

I added all descriptions how to run it there, let me know if you need any help.

Anyway: I distilled the issue thanks to that to invalid `<link>` tag that appears first inside a frame.

**Comment by hadihallak** [comment]
@megawebmaster Thanks! This is going to be super helpful.
will be taking another look early next week just as soon as we sort out some of our high priority work around injection order.

**Comment by megawebmaster** [comment]
Hi @hadihallak - do you have any news on the topic?

**Review by hadihallak — APPROVED** [review]
@megawebmaster We’ve been busy working on other issues and the future React 18 and concurrency work and haven’t had much time to look again into it until today.

I wasn’t able to run your reproduction repo as it was giving me a bunch of storybook/babel errors so I just tested it on a local app and I think the solution you worked on in this PR is good to make sure that ٍStitches isn’t causing any errors when it tries to hydrate the stylesheets by scanning them so this looks good to me and I’m gonna go ahead and merge it. Thank you so much for your patience and for working on a fix for it.

**Pull request merged**
